[package]
name = "swamp-engine"
version = "0.1.0"
edition = "2021"

[features]
default = ["gpu"]
gpu = []

[dependencies]
swamp-gguf = { path = "../swamp-gguf" }
swamp-tensors = { path = "../swamp-tensors" }
swamp-kernels = { path = "../swamp-kernels" }
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
rayon = "1.12.0"
tokenizers = "0.23.1"
serde = { workspace = true, features = ["derive"] }
mlua = { workspace = true }
tracing = { workspace = true }
half = { workspace = true }
libc = { workspace = true }
swamp-gpu = { path = "../swamp-gpu" }
ash = { workspace = true }
crossbeam = "0.8.4"
parking_lot = "0.12.5"
